export const USER_AUTHENTICATION_SUCCESS = "USER_AUTHENTICATION_SUCCESS";
export const USER_AUTHENTICATION_FAIL = "USER_AUTHENTICATION_FAIL";
export const USER_CREATION_SUCCESS = "USER_CREATION_SUCCESS";
export const USER_CREATION_FAIL = "USER_CREATION_FAIL";
